AllCops:
  TargetRubyVersion: 3.1.3
  NewCops: disable
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - bin/*
    - db/**/*
    - config/**/*
    - vendor/**/*
    - Gemfile

Layout/LineLength:
  Max: 90

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Naming/MemoizedInstanceVariableName:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashSyntax: 
  Enabled: false
